// Generated by CoffeeScript 1.6.3
(function() {
  var HomeController;

  HomeController = {
    index: function(req, res) {
      return res.view();
    },

    guestbook: function(req, res){
    	return res.view();
    }
  };

  module.exports = HomeController;

}).call(this);
